apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-user
  template:
    metadata:
      labels:
        app: service-user
    spec:
      containers:
        - name: service-user
          image: ashniu123/thrift-graphql-demo-service-user:v1
          args:
            - -addr=:9090
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - containerPort: 9090
